# This configuration file should contain all required configuration parameters
# for the phylogenetic workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values
inputs:
  - name: ncbi
    metadata: "../ingest/results/metadata.tsv"
    sequences: "../ingest/results/sequences.fasta"

reference: "reference.fasta"
strain_id_field: "accession"

filter:
  exclude: "exclude.txt"
  include: "include.txt"
  min_length: 600

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_filter_iqd: 4

export:
  auspice_config: "auspice_config.json"
  color_by_metadata:
    - clade
    - QC_overall_score
    - QC_overall_status
    - coverage
    - missing_data
    - divergence
    - nonACGTN
    - QC_missing_data
    - QC_mixed_sites
    - QC_rare_mutations
    - QC_frame_shifts
    - QC_stop_codons
    - frame_shifts
    - Private_ReversionSubstitutions
    - Private_LabeledSubstitutions
    - Private_UnlabeledSubstitutions
    - Total_PrivateSubstitutions